config/routes.rb
Rails.application.routes.draw do
  root 'routines#index'
  resources :routines
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/routine.rb
class Routine < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :current_routine, only: [:show,:edit,:update,:destroy]
  def index
    @routines = Routine.all
  end

  def show
  end

  def new
    @routine = Routine.new
  end

  def create
    routine =Routine.create(routine_params)
    redirect_to routines_path,notice:"work created"
  end  

  def edit
  end

  def update
    @routine.update(routine_params)
    redirect_to routines_path,notice:"Work updated"
  end

  def destroy
    @routine.destroy
    redirect_to routines_path,notice:"Work deleted successfully"
  end

  private
  def routine_params
    params.require(:routine).permit(:title , :description)
  end
  def current_routine
    @routine = Routine.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/routines/edit.html.erb
<center>
  <h3>Update Work</h3>
<%= form_with model: @routine do |form| %>
  <%= form.text_field :title, placeholder: "Title" %>
  <%= form.text_field :description, placeholder: "Description" %>

  <%= form.submit %>
<% end %>
</center>

app/views/routines/index.html.erb
<center>

<table>
  <% @routines.each do |routine| %>
    <tr>
      <td><%= link_to routine.title, routine_path(routine) %></td>
      <td><%= button_to 'Edit', edit_routine_path(routine), method: 'get'%></td>
      <td><%= button_to 'Remove', routine_path(routine), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Work", new_routine_path %>
</center>

app/views/routines/new.html.erb
<h3>Add work</h3>
<%= form_with model: @routine do |form| %>
  <%= form.text_field :title, placeholder: "Title" %>
  <%= form.text_field :description, placeholder: "Description" %>

  <%= form.submit %>
<% end %>

app/views/routines/show.html.erb
<center>
<h1><%= @routine.title %></h1>
<h4>"<%= @routine.description %>"</h4>
</center>